DROP TABLE IF EXISTS order_details CASCADE;

DROP TABLE IF EXISTS orders CASCADE;

DROP TABLE IF EXISTS product CASCADE;

DROP TABLE IF EXISTS customer CASCADE;

DROP TABLE IF EXISTS category CASCADE;
